In [1]:
import pandas as pd
from sklearn import linear_model
import numpy as np
import matplotlib.pyplot as plt

In [17]:
url="https://github.com/codebasics/py/raw/master/ML/5_one_hot_encoding/Exercise/carprices.csv"
df= pd.read_csv(url)
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [19]:
dummies=pd.get_dummies(df['Car Model'])
dummies

Audi A5  BMW X5  Mercedez Benz C class
0         0       1                      0
1         0       1                      0
2         0       1                      0
3         0       1                      0
4         0       1                      0
5         1       0                      0
6         1       0                      0
7         1       0                      0
8         1       0                      0
9         0       0                      1
10        0       0                      1
11        0       0                      1
12        0       0                      1

In [20]:
merged= pd.concat([df,dummies],axis='columns')
merged

Car Model  Mileage  Sell Price($)  Age(yrs)  Audi A5  BMW X5  \
0                  BMW X5    69000          18000         6        0       1   
1                  BMW X5    35000          34000         3        0       1   
2                  BMW X5    57000          26100         5        0       1   
3                  BMW X5    22500          40000         2        0       1   
4                  BMW X5    46000          31500         4        0       1   
5                 Audi A5    59000          29400         5        1       0   
6                 Audi A5    52000          32000         5        1       0   
7                 Audi A5    72000          19300         6        1       0   
8                 Audi A5    91000          12000         8        1       0   
9   Mercedez Benz C class    67000          22000         6        0       0   
10  Mercedez Benz C class    83000          20000         7        0       0   
11  Mercedez Benz C class    79000          21000         7        0       0   
12  Mercedez Benz C class    59000          33000         5        0       0   

    Mercedez Benz C class  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0  
5                       0  
6                       0  
7                       0  
8                       0  
9                       1  
10                      1  
11                      1  
12                      1

In [21]:
final = merged.drop(['Car Model','Audi A5'], axis='columns')
final

Mileage  Sell Price($)  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000          18000         6       1                      0
1     35000          34000         3       1                      0
2     57000          26100         5       1                      0
3     22500          40000         2       1                      0
4     46000          31500         4       1                      0
5     59000          29400         5       0                      0
6     52000          32000         5       0                      0
7     72000          19300         6       0                      0
8     91000          12000         8       0                      0
9     67000          22000         6       0                      1
10    83000          20000         7       0                      1
11    79000          21000         7       0                      1
12    59000          33000         5       0                      1

In [22]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [24]:
final.columns

Index(['Mileage', 'Sell Price($)', 'Age(yrs)', 'BMW X5',
       'Mercedez Benz C class'],
      dtype='object')

In [25]:
X = final.drop(['Sell Price($)'], axis='columns')
X

Mileage  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000         6       1                      0
1     35000         3       1                      0
2     57000         5       1                      0
3     22500         2       1                      0
4     46000         4       1                      0
5     59000         5       0                      0
6     52000         5       0                      0
7     72000         6       0                      0
8     91000         8       0                      0
9     67000         6       0                      1
10    83000         7       0                      1
11    79000         7       0                      1
12    59000         5       0                      1

In [27]:
Y= final['Sell Price($)']
Y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [28]:
model.fit(X,Y)

LinearRegression()

In [31]:
model.predict([[35000, 3,1,0]])

array([35286.78445645])

In [32]:
model.predict([[59000, 5, 0, 1]])

array([30477.15426156])

model accuracy

In [33]:
model.score(X,Y)

0.9417050937281084

predicting the price of 4 yr old mercedes benz with 45000 mileage

In [34]:
model.predict([[45000,4,0,1]])

array([36991.31721061])

predicting the price of 7 yr old BMWX with 86000 mileage

In [35]:
model.predict([[86000, 7, 1, 0]])

array([11080.74313219])

In [36]:
model.predict(X)

array([18705.2723644 , 35286.78445645, 24479.19112468, 41245.76426391,
       29882.98779056, 28023.6135243 , 30614.46818502, 21879.57266964,
       12182.34562104, 26183.72387884, 18929.31674102, 20409.80511857,
       30477.15426156])

In [40]:
df.dtypes

Car Model        object
Mileage           int64
Sell Price($)     int64
Age(yrs)          int64
dtype: object

train_test_split with the car model csv

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Mileage        13 non-null     int64
 1   Sell Price($)  13 non-null     int64
 2   Age(yrs)       13 non-null     int64
dtypes: int64(3)
memory usage: 376.0 bytes


In [49]:
from sklearn.model_selection import train_test_split

In [51]:
df

Mileage  Sell Price($)  Age(yrs)
0     69000          18000         6
1     35000          34000         3
2     57000          26100         5
3     22500          40000         2
4     46000          31500         4
5     59000          29400         5
6     52000          32000         5
7     72000          19300         6
8     91000          12000         8
9     67000          22000         6
10    83000          20000         7
11    79000          21000         7
12    59000          33000         5

In [53]:
x=df[['Mileage','Age(yrs)']]
y=df['Sell Price($)']


In [54]:
from sklearn.model_selection import train_test_split

In [58]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [60]:
x_train

Mileage  Age(yrs)
6     52000         5
8     91000         8
2     57000         5
12    59000         5
5     59000         5
10    83000         7
1     35000         3
0     69000         6
4     46000         4
9     67000         6

In [61]:
len(x_test)

3

In [62]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression()

In [63]:
clf.fit(x_train, y_train)

LinearRegression()

In [64]:
clf.predict(x_test)

array([41842.49106079, 22531.68057211, 18423.93325387])

In [65]:
y_test

3     40000
7     19300
11    21000
Name: Sell Price($), dtype: int64

In [66]:
clf.score(x_test,y_test)

0.922481691197174